CREATE TABLE movies (
    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name varchar(512) NOT NULL
) ENGINE=InnoDB;

INSERT INTO movies (name) VALUES ('Les Quatre Cents Coups'); 
INSERT INTO movies (name) VALUES ('La haine'); 
INSERT INTO movies (name) VALUES ('Le Parrain'); 
INSERT INTO movies (name) VALUES ('Le Parrain, 2ᵉ partie'); 
INSERT INTO movies (name) VALUES ('C''est arrivé près de chez vous'); 
INSERT INTO movies (name) VALUES ('Les infiltrés'); 
INSERT INTO movies (name) VALUES ('Umberto D.'); 
INSERT INTO movies (name) VALUES ('L''enfer est à lui'); 
INSERT INTO movies (name) VALUES ('Eddie Murphy Show'); 
INSERT INTO movies (name) VALUES ('À l''Ouest rien de nouveau'); 
INSERT INTO movies (name) VALUES ('Soupe au canard'); 
INSERT INTO movies (name) VALUES ('Mafioso'); 
INSERT INTO movies (name) VALUES ('Stalag 17'); 
INSERT INTO movies (name) VALUES ('Les évadés'); 
INSERT INTO movies (name) VALUES ('The Dark Knight : Le Chevalier noir'); 
INSERT INTO movies (name) VALUES ('Fight Club'); 
INSERT INTO movies (name) VALUES ('Batman Begins'); 
INSERT INTO movies (name) VALUES ('The Big Lebowski'); 
INSERT INTO movies (name) VALUES ('Snatch - Tu braques ou tu raques'); 
INSERT INTO movies (name) VALUES ('Le Bon, la brute, le truand'); 
INSERT INTO movies (name) VALUES ('Gladiator'); 
INSERT INTO movies (name) VALUES ('Il faut sauver le soldat Ryan'); 
INSERT INTO movies (name) VALUES ('Le fabuleux destin d''Amélie Poulain'); 
INSERT INTO movies (name) VALUES ('American History X'); 
INSERT INTO movies (name) VALUES ('Bons baisers de Bruges'); 
INSERT INTO movies (name) VALUES ('Collision (I)'); 
INSERT INTO movies (name) VALUES ('Big Fish'); 
INSERT INTO movies (name) VALUES ('Les 7 Samouraïs'); 
INSERT INTO movies (name) VALUES ('Layer Cake'); 
INSERT INTO movies (name) VALUES ('Un prince à New York'); 
INSERT INTO movies (name) VALUES ('O'' Brother'); 
INSERT INTO movies (name) VALUES ('Friday'); 
INSERT INTO movies (name) VALUES ('Donnie Brasco'); 
INSERT INTO movies (name) VALUES ('Raging Bull'); 
INSERT INTO movies (name) VALUES ('Ed Wood'); 
INSERT INTO movies (name) VALUES ('Peur primale'); 
INSERT INTO movies (name) VALUES ('Les fumistes'); 
INSERT INTO movies (name) VALUES ('Jusqu''au bout du rêve'); 
INSERT INTO movies (name) VALUES ('Mafia blues'); 
INSERT INTO movies (name) VALUES ('Mean Streets'); 
INSERT INTO movies (name) VALUES ('Les douze salopards'); 
INSERT INTO movies (name) VALUES ('Le jour le plus long'); 
INSERT INTO movies (name) VALUES ('Combat de boxe'); 
INSERT INTO movies (name) VALUES ('Le zinzin d''Hollywood'); 
INSERT INTO movies (name) VALUES ('Le dingue du Palace'); 
INSERT INTO movies (name) VALUES ('Six Shooter'); 
INSERT INTO movies (name) VALUES ('The Dark Hours'); 
INSERT INTO movies (name) VALUES ('Edmond'); 
INSERT INTO movies (name) VALUES ('L''âge de vivre'); 
INSERT INTO movies (name) VALUES ('Johnny Mad Dog'); 
INSERT INTO movies (name) VALUES ('L''ennemi public'); 
INSERT INTO movies (name) VALUES ('American Splendor'); 
INSERT INTO movies (name) VALUES ('The Football Factory'); 
INSERT INTO movies (name) VALUES ('Les Pirates du métro'); 
INSERT INTO movies (name) VALUES ('Escrocs mais pas trop'); 
INSERT INTO movies (name) VALUES ('The Business'); 
INSERT INTO movies (name) VALUES ('Belly'); 
INSERT INTO movies (name) VALUES ('Rango'); 
INSERT INTO movies (name) VALUES ('Transformers'); 
INSERT INTO movies (name) VALUES ('Limitless (I)'); 
INSERT INTO movies (name) VALUES ('Pulp Fiction'); 
INSERT INTO movies (name) VALUES ('Star Trek'); 
INSERT INTO movies (name) VALUES ('The Town'); 
INSERT INTO movies (name) VALUES ('300'); 
INSERT INTO movies (name) VALUES ('Heat'); 
INSERT INTO movies (name) VALUES ('La liste de Schindler'); 
INSERT INTO movies (name) VALUES ('Matrix'); 
INSERT INTO movies (name) VALUES ('Les affranchis'); 
INSERT INTO movies (name) VALUES ('Usual Suspects'); 
INSERT INTO movies (name) VALUES ('Là-haut'); 
INSERT INTO movies (name) VALUES ('La folle journée de Ferris Bueller'); 
INSERT INTO movies (name) VALUES ('Ip man'); 
INSERT INTO movies (name) VALUES ('Lolita malgré moi'); 
INSERT INTO movies (name) VALUES ('American Pie'); 
INSERT INTO movies (name) VALUES ('Casino Royale'); 
INSERT INTO movies (name) VALUES ('Retour vers le futur'); 
INSERT INTO movies (name) VALUES ('Le labyrinthe de Pan'); 
